export const lock_example = {
  "title":"Quiz Example",
  "questions":[
    {
      "type":"Lock",
      "value":"¿Cuál es la combinación correcta?",
      "choices":[
        {
          "id":"a",
          "value":"./../assets/images/a.png",
          "answer":true,
        }, 
         {
          "id":"b",
          "value":"./../assets/images/b.png",
          "answer":true,
        },
         {
          "id":"c",
          "value":"./../assets/images/c.png",
          "answer":true,
        },
         {
          "id":"ch",
          "value":"./../assets/images/ch.png",
          "answer":true,
        },
         {
          "id":"d",
          "value":"./../assets/images/d.png",
          "answer":true,
        },
         {
          "id":"e",
          "value":"./../assets/images/e.png",
          "answer":true,
        },
         {
          "id":"f",
          "value":"./../assets/images/f.png",
          "answer":true,
        },
         {
          "id":"g",
          "value":"./../assets/images/g.png",
          "answer":true,
        },
         {
          "id":"h",
          "value":"./../assets/images/h.png",
          "answer":true,
        },
         {
          "id":"i",
          "value":"./../assets/images/i.png",
          "answer":true,
        },
         {
          "id":"j",
          "value":"./../assets/images/j.png",
          "answer":true,
        },
         {
          "id":"k",
          "value":"./../assets/images/k.png",
          "answer":true,
        },
         {
          "id":"l",
          "value":"./../assets/images/l.png",
          "answer":true,
        },
        {
          "id":"m",
          "value":"./../assets/images/m.png",
          "answer":true,
        },
        {
          "id":"n",
          "value":"./../assets/images/n.png",
          "answer":true,
        },
        {
          "id":"o",
          "value":"./../assets/images/o.png",
          "answer":true,
        },
        {
          "id":"p",
          "value":"./../assets/images/p.png",
          "answer":true,
        },
        {
          "id":"q",
          "value":"./../assets/images/q.png",
          "answer":true,
        },
        {
          "id":"r",
          "value":"./../assets/images/r.png",
          "answer":true,
        },
        {
          "id":"s",
          "value":"./../assets/images/s.png",
          "answer":true,
        },
        {
          "id":"t",
          "value":"./../assets/images/t.png",
          "answer":true,
        },
        {
          "id":"u",
          "value":"./../assets/images/u.png",
          "answer":true,
        },
        {
          "id":"x",
          "value":"./../assets/images/x.png",
          "answer":true,
        },
        {
          "id":"y",
          "value":"./../assets/images/y.png",
          "answer":true,
        },
        {
          "id":"z",
          "value":"./../assets/images/z.png",
          "answer":true,
        },
        {
          "id":"1",
          "value":"./../assets/images/t.png",
          "answer":true,
        },
      ],
      "difficulty":2,
    }, 
    
  ],
};
